// This file was auto-generated by ML.NET Model Builder.
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MagicConchShellMaui
{
    public partial class YesNoAI
    {
        /// <summary>
        /// model input class for YesNoAI.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"QuestionLower")]
            public string QuestionLower { get; set; }

            [ColumnName(@"TypeOfQuestion")]
            public float TypeOfQuestion { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for YesNoAI.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"QuestionLower")]
            public float[] QuestionLower { get; set; }

            [ColumnName(@"TypeOfQuestion")]
            public uint TypeOfQuestion { get; set; }

            [ColumnName(@"Features")]
            public float[] Features { get; set; }

            [ColumnName(@"PredictedLabel")]
            public float PredictedLabel { get; set; }

            [ColumnName(@"Score")]
            public float[] Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = "YesNoAI.zip";

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var stream = FileSystem.OpenAppPackageFileAsync(MLNetModelPath).Result;
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(stream, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
